services:
  web:
    build: .
    container_name: app_web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0

  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: app_celery
    command: celery -A celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0

  tailwind:
    image: node:18-slim
    container_name: app_tailwind
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"



  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres: {}
