services:
  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6380:6379"


  tailwind:
    image: node:18-slim
    container_name: app_tailwind
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"


  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  postgres_data: {}
